apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "rasa-x.fullname" . }}-nginx
  labels:
    {{ include "rasa-x.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
{{- with .Values.nginx.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  ports:
  {{- if .Values.nginx.service.enableHttp }}
  - port: {{ .Values.nginx.service.port }}
    targetPort: 8080
    protocol: "TCP"
    name: "http"
    {{- if .Values.nginx.service.nodePort }}
    nodePort: {{ .Values.nginx.service.nodePort }}
    {{- end }}
  {{- end }}
  {{- if .Values.nginx.service.enableHttps }}
  - port: {{ .Values.nginx.service.httpsPort }}
    targetPort: 8443
    protocol: "TCP"
    name: "https"
    {{- if .Values.nginx.service.httpsNodePort }}
    nodePort: {{ .Values.nginx.service.httpsNodePort }}
    {{- end }}
  {{- end }}
    {{- if .Values.nginx.service.externalIPs }}
  externalIPs: {{ .Values.nginx.service.externalIPs | toYaml | nindent 2 }}
    {{- end }}
  type: {{ .Values.nginx.service.type }}
  selector:
    {{- include "rasa-x.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
